# Generated by Django 5.0.3 on 2024-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
